#pragma once

#include"GUI_ImGui.h"
#include"manager.h"
#include"DirectXStruct.h"
#include"DirectX.h"
#include"Time.h"
#include"Object.h"
#include"Component.h"
#include"Behaviour.h"
#include"Transform.h"
#include"Tag.h"
#include"Renderer.h"
#include"GameObject.h"
#include"SceneManager.h"
#include"Input.h"
#include"Audio.h"